---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scmp
  namespace: kube-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scmp
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scmp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scmp
subjects:
- kind: ServiceAccount
  name: scmp
  namespace: kube-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubectl
  name: kubectl
  namespace: kube-admin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubectl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubectl
    spec:
      serviceAccount: scmp
      containers:
      - env:
        - name: APISERVER
          value: "https://10.xx.xx.72:5443"
        - name: CLUSTER
          value: "sgt-cce-prod"
        image: iyacontrol/kubectl:v0.0.1
        imagePullPolicy: Always
        name: kubectl
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 150m
            memory: 150Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30